# Generated by Django 5.1.4 on 2025-01-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufname', models.CharField(max_length=100, unique=True)),
                ('stulname', models.CharField(max_length=100, unique=True)),
                ('stuemail', models.EmailField(max_length=254, unique=True)),
                ('stupassword', models.CharField(max_length=100)),
                ('stumobile', models.CharField(max_length=100)),
            ],
        ),
    ]
